package assets

import (
	"embed"
	"fmt"
	iofs "io/fs"
	"strings"
)

// fs carries the generated runtime assets (compose templates and the
// stab binary, produced by `make assets-common`). They are never
// committed — every user builds them. The personal, build-machine-specific
// piagent assets
// (skills/extensions/packages/models.json/secrets.env) are embedded separately
// behind the `embedassets` build tag — see assets_gen.go and stubs.go — so a
// clean `go build` (no tag) never needs them and never leaks them.
//
//go:embed all:files/ollama all:files/webui all:files/stab all:files/tts
var fs embed.FS

// Read returns a runtime asset, or an error naming what is missing.
func Read(path string) ([]byte, error) {
	b, err := fs.ReadFile("files/" + path)
	if err != nil {
		return nil, fmt.Errorf("runtime asset %q is not embedded in this binary: "+
			"run `make assets-common` and rebuild (%w)", path, err)
	}
	return b, nil
}

// List returns every embedded asset under prefix, as paths relative to files/,
// so a caller can write a whole staged directory back out (the voice backend
// source, for instance). Returns an empty slice when nothing is embedded.
func List(prefix string) ([]string, error) {
	root := "files/" + strings.TrimSuffix(prefix, "/")
	var found []string
	err := iofs.WalkDir(fs, root, func(path string, entry iofs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		found = append(found, strings.TrimPrefix(path, "files/"))
		return nil
	})
	if err != nil {
		return nil, err
	}
	return found, nil
}

// Has reports whether a runtime asset is embedded in this binary.
//
// The generated assets are absent from a fresh clone until `make
// assets-common` runs, so tests that render a template use this to skip rather
// than fail on a checkout nobody has built yet.
func Has(path string) bool {
	_, err := fs.ReadFile("files/" + path)
	return err == nil
}

// MustRead returns a runtime asset, panicking if it is missing.
//
// The embedded directories are generated by `make assets-common`, so a binary
// built by hand from a fresh clone has only the placeholders. Say that, rather
// than passing on a bare "file does not exist".
func MustRead(path string) []byte {
	b, err := fs.ReadFile("files/" + path)
	if err != nil {
		panic(fmt.Sprintf(
			"runtime asset %q is not embedded in this binary: run `make assets-common` and rebuild (%v)",
			path, err,
		))
	}
	return b
}
