//go:build embedassets

package assets

import "embed"

// piagentFS embeds the build machine's personal piagent assets, regenerated by
// `make assets` (cmd/embedgen) into internal/assets/files/piagent/. This file is
// gitignored: it only exists on machines that ran the full build, and its
// contents (skills, extensions, packages) must never be committed.
//
// The embedded names are listed explicitly rather than `all:files/piagent` so a
// stale models.json or secrets.env left in that directory by an older build
// cannot be shipped inside the binary. Pi's model providers and API keys travel
// only through the `embedsecrets` tier (internal/assets/home_gen.go), never here.
//
//go:embed files/piagent/skills.tgz files/piagent/extensions.tgz files/piagent/npm.tgz files/piagent/git.tgz files/piagent/settings.json
var piagentFS embed.FS

// PiAgentFile returns a baked piagent asset (skills/extensions/npm/git
// tarballs, settings.json), or nil when absent.
func PiAgentFile(name string) []byte {
	b, err := piagentFS.ReadFile("files/piagent/" + name)
	if err != nil {
		return nil
	}
	return b
}
