//go:build embedsecrets

package assets

import "embed"

// homeFS embeds the build machine's models.json + secrets.env, regenerated by
// `make assets` (cmd/embedgen) into internal/assets/files/home/. This file is
// gitignored: it only exists on machines that ran the full build, and its
// contents (provider models and API keys) must never be committed.
//
//go:embed all:files/home
var homeFS embed.FS

// HomeFile returns a baked home asset (models.json or secrets.env), or nil.
func HomeFile(name string) []byte {
	b, err := homeFS.ReadFile("files/home/" + name)
	if err != nil {
		return nil
	}
	return b
}
